package com.attendance.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attendancedetails generated by hbm2java
 */
@Entity
@Table(name = "attendancedetails", catalog = "test")
public class AttendanceDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer attendanceId;
	private Employee employee;
	private MachineDetails machinedetails;
	private Date swipeIn;
	private Date swipeOut;
	private Integer totalHours;

	public AttendanceDetails() {
	}

	public AttendanceDetails(Employee employee, MachineDetails machinedetails) {
		this.employee = employee;
		this.machinedetails = machinedetails;
	}

	public AttendanceDetails(Employee employee, MachineDetails machinedetails, Date swipeIn, Date swipeOut,
			Integer totalHours) {
		this.employee = employee;
		this.machinedetails = machinedetails;
		this.swipeIn = swipeIn;
		this.swipeOut = swipeOut;
		this.totalHours = totalHours;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "attendance_id", unique = true, nullable = false)
	public Integer getAttendanceId() {
		return this.attendanceId;
	}

	public void setAttendanceId(Integer attendanceId) {
		this.attendanceId = attendanceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "employeeid", referencedColumnName = "employeeid", nullable = false),
			@JoinColumn(name = "access_cardno", referencedColumnName = "access_cardno", nullable = false) })
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "machine_id", nullable = false)
	public MachineDetails getMachinedetails() {
		return this.machinedetails;
	}

	public void setMachinedetails(MachineDetails machinedetails) {
		this.machinedetails = machinedetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "swipe_in", length = 19)
	public Date getSwipeIn() {
		return this.swipeIn;
	}

	public void setSwipeIn(Date swipeIn) {
		this.swipeIn = swipeIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "swipe_out", length = 19)
	public Date getSwipeOut() {
		return this.swipeOut;
	}

	public void setSwipeOut(Date swipeOut) {
		this.swipeOut = swipeOut;
	}

	@Column(name = "total_hours")
	public Integer getTotalHours() {
		return this.totalHours;
	}

	public void setTotalHours(Integer totalHours) {
		this.totalHours = totalHours;
	}

}
