package com.attendance.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "test")
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private EmployeeId id;
	private MachineDetails machinedetails;
	private String firstname;
	private String lastname;
	private String status;
	private String usertype;
	  private Set<AttendanceDetails> attendancedetailses = new HashSet<AttendanceDetails>();
	

	public Employee() {
	}

	public Employee(EmployeeId id, MachineDetails machinedetails, String firstname, String lastname, String status,
			String usertype) {
		this.id = id;
		this.machinedetails = machinedetails;
		this.firstname = firstname;
		this.lastname = lastname;
		this.status = status;
		this.usertype = usertype;
	}

	public Employee(EmployeeId id, MachineDetails machinedetails, String firstname, String lastname, String status,
			String usertype, Set attendancedetailses) {
		this.id = id;
		this.machinedetails = machinedetails;
		this.firstname = firstname;
		this.lastname = lastname;
		this.status = status;
		this.usertype = usertype;
		this.attendancedetailses = attendancedetailses;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "employeeid", column = @Column(name = "employeeid", nullable = false)),
			@AttributeOverride(name = "accessCardno", column = @Column(name = "access_cardno", nullable = false, length = 20)) })
	public EmployeeId getId() {
		return this.id;
	}

	public void setId(EmployeeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "machine_id", nullable = false)
	public MachineDetails getMachinedetails() {
		return this.machinedetails;
	}

	public void setMachinedetails(MachineDetails machinedetails) {
		this.machinedetails = machinedetails;
	}

	@Column(name = "firstname", nullable = false, length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "usertype", nullable = false, length = 10)
	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<AttendanceDetails> getAttendancedetailses() {
		return this.attendancedetailses;
	}

	public void setAttendancedetailses(Set<AttendanceDetails> attendancedetailses) {
		this.attendancedetailses = attendancedetailses;
	}

}